-- --------------------------------------------------------
-- Caserita Smart: Tabla de Alertas de Seguridad (Modo Pánico)
-- --------------------------------------------------------

CREATE TABLE IF NOT EXISTS alertas_seguridad (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_casero UUID,
    tipo_alerta VARCHAR(50) DEFAULT 'PANICO',
    fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    resuelto BOOLEAN DEFAULT FALSE,
    origen VARCHAR(50) DEFAULT 'BotonUI' -- Puede ser 'BotonUI' o 'Voz'
);

-- Políticas de Seguridad (RLS)
ALTER TABLE alertas_seguridad ENABLE ROW LEVEL SECURITY;

-- 1. Los cajeros solo pueden crear alertas para su propia bodega (o para el dueño)
CREATE POLICY "Permitir inserts a cualquier usuario autenticado" ON alertas_seguridad
    FOR INSERT 
    TO authenticated 
    WITH CHECK (auth.uid() IS NOT NULL);

-- 2. Lectura solo para el dueño
CREATE POLICY "Dueño lee sus propias alertas" ON alertas_seguridad
    FOR SELECT 
    TO authenticated 
    USING (cod_casero = auth.uid());
