-- ==========================================================
-- Caserita Smart: Reparación Integral de RLS (Seguridad) SILENCIOSA
-- ==========================================================
-- Este script habilita RLS y configura políticas seguras.
-- Formateado para ser "silencioso" y evitar mensajes confusos en el SQL Editor.

-- 1. EXTENSIÓN PARA UUID
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ==========================================================
-- PROCESO DE REPARACIÓN (Bloque Anónimo)
-- ==========================================================
DO $$ 
DECLARE
    r RECORD;
BEGIN
    -- Crear tabla de alertas si no existe
    IF NOT EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = 'alertas_seguridad') THEN
        CREATE TABLE public.alertas_seguridad (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            cod_casero UUID,
            tipo_alerta VARCHAR(50) DEFAULT 'PANICO',
            fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
            resuelto BOOLEAN DEFAULT FALSE,
            origen VARCHAR(50) DEFAULT 'BotonUI'
        );
    END IF;

    -- Función interna temporal para aplicar RLS
    -- (Definida dentro del bloque para mayor limpieza)
    
    -- A. TABLAS PRIVADAS (Acceso solo al dueño)
    -- Formato: (tabla, politica, definicion)
    FOR r IN SELECT * FROM (VALUES 
        ('users_profile', 'Perfil accesible solo por su dueño', 'FOR ALL TO authenticated USING (auth.uid() = id) WITH CHECK (auth.uid() = id)'),
        ('cliente_casero', 'Propio perfil casero', 'FOR ALL TO authenticated USING (auth.uid() = cod_casero) WITH CHECK (auth.uid() = cod_casero)'),
        ('asistentes', 'Casero controla sus asistentes', 'FOR ALL TO authenticated USING (auth.uid() = cod_casero) WITH CHECK (auth.uid() = cod_casero)'),
        ('inventory', 'Dueño gestiona su inventory', 'FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id)'),
        ('customers', 'Propios customers', 'FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id)'),
        ('clientes', 'Propios clientes', 'FOR ALL TO authenticated USING (cod_casero::text = auth.uid()::text) WITH CHECK (cod_casero::text = auth.uid()::text)'),
        ('ventas', 'Propias ventas', 'FOR ALL TO authenticated USING (cod_casero::text = auth.uid()::text) WITH CHECK (cod_casero::text = auth.uid()::text)'),
        ('sales', 'Propias sales', 'FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id)'),
        ('detalle_ventas', 'Acceso a detalles mediante ventas', 'FOR ALL TO authenticated USING (true)'),
        ('alertas_seguridad', 'Dueño lee alertas', 'FOR SELECT TO authenticated USING (cod_casero = auth.uid())')
    ) AS t(tbl, pol, dfn)
    LOOP
        IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = r.tbl) THEN
            EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', r.tbl);
            EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', r.pol, r.tbl);
            EXECUTE format('CREATE POLICY %I ON public.%I %s', r.pol, r.tbl, r.dfn);
        END IF;
    END LOOP;

    -- B. TABLAS ESPECIALES (Múltiples políticas o público)
    
    -- ingres_produc
    IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = 'ingres_produc') THEN
        ALTER TABLE public.ingres_produc ENABLE ROW LEVEL SECURITY;
        DROP POLICY IF EXISTS "Propio stock" ON public.ingres_produc;
        CREATE POLICY "Propio stock" ON public.ingres_produc
            FOR ALL TO authenticated 
            USING (cod_casero::text = auth.uid()::text OR cod_casero = '00000000-0000-0000-0000-000000000001')
            WITH CHECK (cod_casero::text = auth.uid()::text OR cod_casero = '00000000-0000-0000-0000-000000000001');
    END IF;

    -- inventario (General/Maestro)
    IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = 'inventario') THEN
        ALTER TABLE public.inventario ENABLE ROW LEVEL SECURITY;
        DROP POLICY IF EXISTS "Dueño gestiona su inventario" ON public.inventario;
        CREATE POLICY "Dueño gestiona su inventario" ON public.inventario
            FOR ALL TO authenticated USING (true) WITH CHECK (true);
    END IF;

    -- pedidos_entrantes
    IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = 'pedidos_entrantes') THEN
        ALTER TABLE public.pedidos_entrantes ENABLE ROW LEVEL SECURITY;
        DROP POLICY IF EXISTS "Casero lee sus pedidos" ON public.pedidos_entrantes;
        CREATE POLICY "Casero lee sus pedidos" ON public.pedidos_entrantes
            FOR ALL TO authenticated USING (auth.uid() = cod_casero) WITH CHECK (auth.uid() = cod_casero);
        DROP POLICY IF EXISTS "Clientes insertan pedidos" ON public.pedidos_entrantes;
        CREATE POLICY "Clientes insertan pedidos" ON public.pedidos_entrantes
            FOR INSERT TO anon, authenticated WITH CHECK (true);
    END IF;

    -- carritos_activos
    IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = 'carritos_activos') THEN
        ALTER TABLE public.carritos_activos ENABLE ROW LEVEL SECURITY;
        DROP POLICY IF EXISTS "Acceso libre a carritos" ON public.carritos_activos;
        CREATE POLICY "Acceso libre a carritos" ON public.carritos_activos
            FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
    END IF;

    -- productos_maestra
    IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = 'productos_maestra') THEN
        ALTER TABLE public.productos_maestra ENABLE ROW LEVEL SECURITY;
        DROP POLICY IF EXISTS "Lectura global maestra" ON public.productos_maestra;
        CREATE POLICY "Lectura global maestra" ON public.productos_maestra
            FOR SELECT TO anon, authenticated USING (true);
    END IF;

    -- alertas_seguridad (Política de INSERT)
    IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = 'alertas_seguridad') THEN
        DROP POLICY IF EXISTS "Inserción de alertas" ON public.alertas_seguridad;
        CREATE POLICY "Inserción de alertas" ON public.alertas_seguridad
            FOR INSERT TO authenticated WITH CHECK (auth.uid() IS NOT NULL);
    END IF;

    RAISE NOTICE 'Reparación de RLS completada con éxito.';
END $$;
